### ISSUE TITLE
Add styled-normalize 

### ISSUE THREAD

**Issue by hjeti** [mediamonks/cra-template#5]
this package will include `normalize.css`

**Comment by psimk** [comment]
this should also go to https://github.com/mediamonks/cra-template-standard

**Comment by psimk** [comment]
I'm also not convinced that we specifically need the `styled` version of `normalize.css`. CRA is configured to support css imports, so all it should take is importing https://github.com/necolas/normalize.css.

**Comment by hjeti** [comment]
yes that is also an option. I moved it to the other repo.
